Fix compilation error: add 3rd param to Assets.at
Use false because it is the default value mentionned on the scala doc:
http://www.playframework.com/documentation/2.3.x/api/scala/index.html#controllers.Assets$